"""Add logs for post & gold modifications and set deleted posts not remove from database

Revision ID: 2f8edd438f0d
Revises: 3d2b970dcd9c
Create Date: 2024-05-18 21:34:47.599131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8edd438f0d'
down_revision = '3d2b970dcd9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_posts_claimerID'), ['claimerID'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_posterID'), ['posterID'], unique=False)

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responses_postID'), ['postID'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_postID'))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_posterID'))
        batch_op.drop_index(batch_op.f('ix_posts_claimerID'))
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
