"""Add column for a user's available gold

Revision ID: 3d2b970dcd9c
Revises: 8f3fa636f4a8
Create Date: 2024-05-11 13:26:24.078627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2b970dcd9c'
down_revision = '8f3fa636f4a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gold_available', sa.BigInteger(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gold_available')

    # ### end Alembic commands ###
